name: Tests
on:
  pull_request:

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - uses: reviewdog/action-rubocop@v2

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - uses: reviewdog/action-brakeman@v2
        with:
          brakeman_flags: --except CheckEOLRails

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - uses: reviewdog/action-misspell@v1
        with:
          locale: "US"

  test-rails:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          ## test against ruby versions from the last two release cycles
          ##
          ## cf https://endoflife.date/ruby
          # 2021-04-05 releases
          - 3.0.1
          # 2021-07-07 releases
          - 3.0.2
          # 2023-02-08 release
          - 3.2.1
          # 2023-03-30 release
          - 3.2.2
          # 2023-12-25 release
          - 3.3.0
        rails:
          ## test against last two releases from supported rails versions
          ## when updating, be sure to add the matching version Gemfile to
          ## .github/gemfiles
          ##
          ## cf https://endoflife.date/rails
          # 2021-05-06 releases
          - 6.0.3.7
          - 6.1.3.2
          # 2021-08-20 releases
          - 6.0.4.1
          - 6.1.4.1
          # 2023-01-24 releases
          - 6.1.7.2
          # 2023-03-13 releases
          - 6.1.7.3
          # 2023-03-13 releases
          - 7.0.4.3
          # 2023-10-05 releases
          - 7.1
        exclude:
          ## be careful with which versions of ruby does rails support
          ## cf https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
          # rails 6.0 requires ruby < 3
          - rails: 6.0.3.7
            ruby: 3.0.1
          - rails: 6.0.3.7
            ruby: 3.0.2
          - rails: 6.0.4.1
            ruby: 3.0.1
          - rails: 6.0.4.1
            ruby: 3.0.2
          - rails: 6.0.3.7
            ruby: 3.2.1
          - rails: 6.0.4.1
            ruby: 3.2.1
          - rails: 6.1.3.2
            ruby: 3.2.1
          - rails: 6.0.3.7
            ruby: 3.2.2
          - rails: 6.0.4.1
            ruby: 3.2.2
          - rails: 6.1.3.2
            ruby: 3.2.2
          - rails: 6.0.3.7
            ruby: 3.3.0
          - rails: 6.0.4.1
            ruby: 3.3.0
          - rails: 6.1.3.2
            ruby: 3.3.0

    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ github.workspace }}/.github/gemfiles/rails-${{ matrix.rails }}.Gemfile

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare database
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rake spec
